
name: kalkulator_ayam_kub
description: Kalkulator pakan ayam KUB dengan export laporan
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.68.0
  syncfusion_flutter_xlsio: ^27.1.50
  syncfusion_flutter_pdf: ^27.1.50
  path_provider: ^2.1.3
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
